### ISSUE TITLE
Rút gọn thanh sidebar 

### ISSUE THREAD

**Issue by tamvtok321** [DH20LT/Cay-Thue#23]
Danh sách các mục cần bỏ, hoặc ẩn đi:
- [ ] Danh sách đang được xem xét
- [ ] 

![335998905_1199352997369563_3165347509248593068_n](https://user-images.githubusercontent.com/73837205/226363669-fbd07c67-4ebc-4e62-aeb7-81feeecc3357.png)

**Comment by TaQuangKhoi** [comment]
@tamvtok321 Vậy tui sẽ xóa các mục đó nhé.

**Comment by tamvtok321** [comment]
mà cái Lịch sử bán hàng, thì có thể mình sẽ dùng đó chứ. Mà ma' để 1 mục thế kia để mỗi có cái Lịch sử bán hàng thì nó lại hơi kì xD
